DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS movies CASCADE;
DROP TABLE IF EXISTS nominations CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  username VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL
);

CREATE TABLE movies (
  id SERIAL PRIMARY KEY NOT NULL,
  title VARCHAR(255) NOT NULL,
  year INTEGER,
  imdbID VARCHAR(255) NOT NULL
);

CREATE TABLE nominations (
  id SERIAL PRIMARY KEY NOT NULL,
  users_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  movies_id INTEGER REFERENCES movies(id) ON DELETE CASCADE,
  time TIMESTAMP NOT NULL DEFAULT Now()  
);
